name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install System packages
      run: sudo apt-get install -y libxcb-xinerama0
    - name: Run Tests
      env:
        QT_QPA_PLATFORM: offscreen
        DJANGO_DEBUG: 'False'
      working-directory: ./OnlineVersion
      run: |
        python manage.py test
